/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "wine-11.6-90-g75341a9855f0"
#endif /* AVUTIL_FFVERSION_H */
