%ifndef ARCH_AARCH64
%define ARCH_AARCH64 0
%endif
%ifndef ARCH_ARM
%define ARCH_ARM 0
%endif
%ifndef ARCH_IA64
%define ARCH_IA64 0
%endif
%ifndef ARCH_LOONGARCH
%define ARCH_LOONGARCH 0
%endif
%ifndef ARCH_LOONGARCH32
%define ARCH_LOONGARCH32 0
%endif
%ifndef ARCH_LOONGARCH64
%define ARCH_LOONGARCH64 0
%endif
%ifndef ARCH_M68K
%define ARCH_M68K 0
%endif
%ifndef ARCH_MIPS
%define ARCH_MIPS 0
%endif
%ifndef ARCH_MIPS64
%define ARCH_MIPS64 0
%endif
%ifndef ARCH_PARISC
%define ARCH_PARISC 0
%endif
%ifndef ARCH_PPC
%define ARCH_PPC 0
%endif
%ifndef ARCH_PPC64
%define ARCH_PPC64 0
%endif
%ifndef ARCH_RISCV
%define ARCH_RISCV 0
%endif
%ifndef ARCH_S390
%define ARCH_S390 0
%endif
%ifndef ARCH_SPARC
%define ARCH_SPARC 0
%endif
%ifndef ARCH_SPARC64
%define ARCH_SPARC64 0
%endif
%ifndef ARCH_TILEGX
%define ARCH_TILEGX 0
%endif
%ifndef ARCH_TILEPRO
%define ARCH_TILEPRO 0
%endif
%ifndef ARCH_WASM
%define ARCH_WASM 0
%endif
%ifndef ARCH_X86
%define ARCH_X86 0
%endif
%ifndef ARCH_X86_32
%define ARCH_X86_32 0
%endif
%ifndef ARCH_X86_64
%define ARCH_X86_64 0
%endif
%ifndef HAVE_ACCESS
%define HAVE_ACCESS 0
%endif
%ifndef HAVE_AESNI_EXTERNAL
%define HAVE_AESNI_EXTERNAL 0
%endif
%ifndef HAVE_AESNI_INLINE
%define HAVE_AESNI_INLINE 0
%endif
%ifndef HAVE_ALIGNED_MALLOC
%define HAVE_ALIGNED_MALLOC 0
%endif
%ifndef HAVE_ALIGNED_STACK
%define HAVE_ALIGNED_STACK 0
%endif
%ifndef HAVE_ALTIVEC_EXTERNAL
%define HAVE_ALTIVEC_EXTERNAL 0
%endif
%ifndef HAVE_ALTIVEC_INLINE
%define HAVE_ALTIVEC_INLINE 0
%endif
%ifndef HAVE_AMD3DNOWEXT_EXTERNAL
%define HAVE_AMD3DNOWEXT_EXTERNAL 0
%endif
%ifndef HAVE_AMD3DNOWEXT_INLINE
%define HAVE_AMD3DNOWEXT_INLINE 0
%endif
%ifndef HAVE_AMD3DNOW_EXTERNAL
%define HAVE_AMD3DNOW_EXTERNAL 0
%endif
%ifndef HAVE_AMD3DNOW_INLINE
%define HAVE_AMD3DNOW_INLINE 0
%endif
%ifndef HAVE_ARC4RANDOM_BUF
%define HAVE_ARC4RANDOM_BUF 0
%endif
%ifndef HAVE_ARMV5TE_EXTERNAL
%define HAVE_ARMV5TE_EXTERNAL 0
%endif
%ifndef HAVE_ARMV5TE_INLINE
%define HAVE_ARMV5TE_INLINE 0
%endif
%ifndef HAVE_ARMV6T2_EXTERNAL
%define HAVE_ARMV6T2_EXTERNAL 0
%endif
%ifndef HAVE_ARMV6T2_INLINE
%define HAVE_ARMV6T2_INLINE 0
%endif
%ifndef HAVE_ARMV6_EXTERNAL
%define HAVE_ARMV6_EXTERNAL 0
%endif
%ifndef HAVE_ARMV6_INLINE
%define HAVE_ARMV6_INLINE 0
%endif
%ifndef HAVE_ARMV8_EXTERNAL
%define HAVE_ARMV8_EXTERNAL 0
%endif
%ifndef HAVE_ARMV8_INLINE
%define HAVE_ARMV8_INLINE 0
%endif
%ifndef HAVE_ARM_CRC_EXTERNAL
%define HAVE_ARM_CRC_EXTERNAL 0
%endif
%ifndef HAVE_ARM_CRC_INLINE
%define HAVE_ARM_CRC_INLINE 0
%endif
%ifndef HAVE_ARPA_INET_H
%define HAVE_ARPA_INET_H 0
%endif
%ifndef HAVE_ASM_HWPROBE_H
%define HAVE_ASM_HWPROBE_H 0
%endif
%ifndef HAVE_ASM_MOD_Q
%define HAVE_ASM_MOD_Q 0
%endif
%ifndef HAVE_ASM_TYPES_H
%define HAVE_ASM_TYPES_H 0
%endif
%ifndef HAVE_AS_ARCHEXT_CRC_DIRECTIVE
%define HAVE_AS_ARCHEXT_CRC_DIRECTIVE 0
%endif
%ifndef HAVE_AS_ARCHEXT_DOTPROD_DIRECTIVE
%define HAVE_AS_ARCHEXT_DOTPROD_DIRECTIVE 0
%endif
%ifndef HAVE_AS_ARCHEXT_I8MM_DIRECTIVE
%define HAVE_AS_ARCHEXT_I8MM_DIRECTIVE 0
%endif
%ifndef HAVE_AS_ARCHEXT_SME2_DIRECTIVE
%define HAVE_AS_ARCHEXT_SME2_DIRECTIVE 0
%endif
%ifndef HAVE_AS_ARCHEXT_SME_DIRECTIVE
%define HAVE_AS_ARCHEXT_SME_DIRECTIVE 0
%endif
%ifndef HAVE_AS_ARCHEXT_SME_I16I64_DIRECTIVE
%define HAVE_AS_ARCHEXT_SME_I16I64_DIRECTIVE 0
%endif
%ifndef HAVE_AS_ARCHEXT_SVE2_DIRECTIVE
%define HAVE_AS_ARCHEXT_SVE2_DIRECTIVE 0
%endif
%ifndef HAVE_AS_ARCHEXT_SVE_DIRECTIVE
%define HAVE_AS_ARCHEXT_SVE_DIRECTIVE 0
%endif
%ifndef HAVE_AS_ARCH_DIRECTIVE
%define HAVE_AS_ARCH_DIRECTIVE 0
%endif
%ifndef HAVE_AS_DN_DIRECTIVE
%define HAVE_AS_DN_DIRECTIVE 0
%endif
%ifndef HAVE_AS_FPU_DIRECTIVE
%define HAVE_AS_FPU_DIRECTIVE 0
%endif
%ifndef HAVE_AS_FUNC
%define HAVE_AS_FUNC 0
%endif
%ifndef HAVE_AS_OBJECT_ARCH
%define HAVE_AS_OBJECT_ARCH 0
%endif
%ifndef HAVE_ATAN2F
%define HAVE_ATAN2F 0
%endif
%ifndef HAVE_ATANF
%define HAVE_ATANF 0
%endif
%ifndef HAVE_AVX2_EXTERNAL
%define HAVE_AVX2_EXTERNAL 0
%endif
%ifndef HAVE_AVX2_INLINE
%define HAVE_AVX2_INLINE 0
%endif
%ifndef HAVE_AVX512ICL_EXTERNAL
%define HAVE_AVX512ICL_EXTERNAL 0
%endif
%ifndef HAVE_AVX512ICL_INLINE
%define HAVE_AVX512ICL_INLINE 0
%endif
%ifndef HAVE_AVX512_EXTERNAL
%define HAVE_AVX512_EXTERNAL 0
%endif
%ifndef HAVE_AVX512_INLINE
%define HAVE_AVX512_INLINE 0
%endif
%ifndef HAVE_AVX_EXTERNAL
%define HAVE_AVX_EXTERNAL 0
%endif
%ifndef HAVE_AVX_INLINE
%define HAVE_AVX_INLINE 0
%endif
%ifndef HAVE_BCRYPT
%define HAVE_BCRYPT 0
%endif
%ifndef HAVE_BIGENDIAN
%define HAVE_BIGENDIAN 0
%endif
%ifndef HAVE_BLOCKS_EXTENSION
%define HAVE_BLOCKS_EXTENSION 0
%endif
%ifndef HAVE_CBRT
%define HAVE_CBRT 0
%endif
%ifndef HAVE_CBRTF
%define HAVE_CBRTF 0
%endif
%ifndef HAVE_CDIO_PARANOIA_H
%define HAVE_CDIO_PARANOIA_H 0
%endif
%ifndef HAVE_CDIO_PARANOIA_PARANOIA_H
%define HAVE_CDIO_PARANOIA_PARANOIA_H 0
%endif
%ifndef HAVE_CLMUL_EXTERNAL
%define HAVE_CLMUL_EXTERNAL 0
%endif
%ifndef HAVE_CLMUL_INLINE
%define HAVE_CLMUL_INLINE 0
%endif
%ifndef HAVE_CLOCK_GETTIME
%define HAVE_CLOCK_GETTIME 0
%endif
%ifndef HAVE_CLOSESOCKET
%define HAVE_CLOSESOCKET 0
%endif
%ifndef HAVE_COMMANDLINETOARGVW
%define HAVE_COMMANDLINETOARGVW 0
%endif
%ifndef HAVE_COPYSIGN
%define HAVE_COPYSIGN 0
%endif
%ifndef HAVE_COSF
%define HAVE_COSF 0
%endif
%ifndef HAVE_CUDA_H
%define HAVE_CUDA_H 0
%endif
%ifndef HAVE_DCBZL_EXTERNAL
%define HAVE_DCBZL_EXTERNAL 0
%endif
%ifndef HAVE_DCBZL_INLINE
%define HAVE_DCBZL_INLINE 0
%endif
%ifndef HAVE_DIRECT_H
%define HAVE_DIRECT_H 0
%endif
%ifndef HAVE_DIRENT_H
%define HAVE_DIRENT_H 0
%endif
%ifndef HAVE_DISPATCH_DISPATCH_H
%define HAVE_DISPATCH_DISPATCH_H 0
%endif
%ifndef HAVE_DOS_PATHS
%define HAVE_DOS_PATHS 0
%endif
%ifndef HAVE_DOTPROD_EXTERNAL
%define HAVE_DOTPROD_EXTERNAL 0
%endif
%ifndef HAVE_DOTPROD_INLINE
%define HAVE_DOTPROD_INLINE 0
%endif
%ifndef HAVE_DPI_AWARENESS_CONTEXT
%define HAVE_DPI_AWARENESS_CONTEXT 0
%endif
%ifndef HAVE_DXGIDEBUG_H
%define HAVE_DXGIDEBUG_H 0
%endif
%ifndef HAVE_DXVA_H
%define HAVE_DXVA_H 0
%endif
%ifndef HAVE_EBP_AVAILABLE
%define HAVE_EBP_AVAILABLE 0
%endif
%ifndef HAVE_EBX_AVAILABLE
%define HAVE_EBX_AVAILABLE 0
%endif
%ifndef HAVE_ELF_AUX_INFO
%define HAVE_ELF_AUX_INFO 0
%endif
%ifndef HAVE_ERF
%define HAVE_ERF 0
%endif
%ifndef HAVE_ES2_GL_H
%define HAVE_ES2_GL_H 0
%endif
%ifndef HAVE_EXP2
%define HAVE_EXP2 0
%endif
%ifndef HAVE_EXP2F
%define HAVE_EXP2F 0
%endif
%ifndef HAVE_EXPF
%define HAVE_EXPF 0
%endif
%ifndef HAVE_FAST_64BIT
%define HAVE_FAST_64BIT 0
%endif
%ifndef HAVE_FAST_CLZ
%define HAVE_FAST_CLZ 0
%endif
%ifndef HAVE_FAST_CMOV
%define HAVE_FAST_CMOV 0
%endif
%ifndef HAVE_FAST_FLOAT16
%define HAVE_FAST_FLOAT16 0
%endif
%ifndef HAVE_FAST_UNALIGNED
%define HAVE_FAST_UNALIGNED 0
%endif
%ifndef HAVE_FCNTL
%define HAVE_FCNTL 0
%endif
%ifndef HAVE_FMA3_EXTERNAL
%define HAVE_FMA3_EXTERNAL 0
%endif
%ifndef HAVE_FMA3_INLINE
%define HAVE_FMA3_INLINE 0
%endif
%ifndef HAVE_FMA4_EXTERNAL
%define HAVE_FMA4_EXTERNAL 0
%endif
%ifndef HAVE_FMA4_INLINE
%define HAVE_FMA4_INLINE 0
%endif
%ifndef HAVE_GETADDRINFO
%define HAVE_GETADDRINFO 0
%endif
%ifndef HAVE_GETAUXVAL
%define HAVE_GETAUXVAL 0
%endif
%ifndef HAVE_GETENV
%define HAVE_GETENV 0
%endif
%ifndef HAVE_GETHRTIME
%define HAVE_GETHRTIME 0
%endif
%ifndef HAVE_GETMODULEHANDLE
%define HAVE_GETMODULEHANDLE 0
%endif
%ifndef HAVE_GETOPT
%define HAVE_GETOPT 0
%endif
%ifndef HAVE_GETPROCESSAFFINITYMASK
%define HAVE_GETPROCESSAFFINITYMASK 0
%endif
%ifndef HAVE_GETPROCESSMEMORYINFO
%define HAVE_GETPROCESSMEMORYINFO 0
%endif
%ifndef HAVE_GETPROCESSTIMES
%define HAVE_GETPROCESSTIMES 0
%endif
%ifndef HAVE_GETRUSAGE
%define HAVE_GETRUSAGE 0
%endif
%ifndef HAVE_GETSTDHANDLE
%define HAVE_GETSTDHANDLE 0
%endif
%ifndef HAVE_GETSYSTEMTIMEASFILETIME
%define HAVE_GETSYSTEMTIMEASFILETIME 0
%endif
%ifndef HAVE_GETTIMEOFDAY
%define HAVE_GETTIMEOFDAY 0
%endif
%ifndef HAVE_GLOB
%define HAVE_GLOB 0
%endif
%ifndef HAVE_GLXGETPROCADDRESS
%define HAVE_GLXGETPROCADDRESS 0
%endif
%ifndef HAVE_GMTIME_R
%define HAVE_GMTIME_R 0
%endif
%ifndef HAVE_GNU_AS
%define HAVE_GNU_AS 0
%endif
%ifndef HAVE_GNU_WINDRES
%define HAVE_GNU_WINDRES 0
%endif
%ifndef HAVE_GSM_H
%define HAVE_GSM_H 0
%endif
%ifndef HAVE_GZIP
%define HAVE_GZIP 0
%endif
%ifndef HAVE_HYPOT
%define HAVE_HYPOT 0
%endif
%ifndef HAVE_I686_EXTERNAL
%define HAVE_I686_EXTERNAL 0
%endif
%ifndef HAVE_I686_INLINE
%define HAVE_I686_INLINE 0
%endif
%ifndef HAVE_I8MM_EXTERNAL
%define HAVE_I8MM_EXTERNAL 0
%endif
%ifndef HAVE_I8MM_INLINE
%define HAVE_I8MM_INLINE 0
%endif
%ifndef HAVE_IBM_ASM
%define HAVE_IBM_ASM 0
%endif
%ifndef HAVE_IDIRECT3DDXGIINTERFACEACCESS
%define HAVE_IDIRECT3DDXGIINTERFACEACCESS 0
%endif
%ifndef HAVE_IDXGIOUTPUT5
%define HAVE_IDXGIOUTPUT5 0
%endif
%ifndef HAVE_INET_ATON
%define HAVE_INET_ATON 0
%endif
%ifndef HAVE_INLINE_ASM
%define HAVE_INLINE_ASM 0
%endif
%ifndef HAVE_INLINE_ASM_DIRECT_SYMBOL_REFS
%define HAVE_INLINE_ASM_DIRECT_SYMBOL_REFS 0
%endif
%ifndef HAVE_INLINE_ASM_LABELS
%define HAVE_INLINE_ASM_LABELS 0
%endif
%ifndef HAVE_INLINE_ASM_NONLOCAL_LABELS
%define HAVE_INLINE_ASM_NONLOCAL_LABELS 0
%endif
%ifndef HAVE_INTRINSICS_NEON
%define HAVE_INTRINSICS_NEON 0
%endif
%ifndef HAVE_INTRINSICS_SSE2
%define HAVE_INTRINSICS_SSE2 0
%endif
%ifndef HAVE_IOCTL_POSIX
%define HAVE_IOCTL_POSIX 0
%endif
%ifndef HAVE_IO_H
%define HAVE_IO_H 0
%endif
%ifndef HAVE_ISATTY
%define HAVE_ISATTY 0
%endif
%ifndef HAVE_ISFINITE
%define HAVE_ISFINITE 0
%endif
%ifndef HAVE_ISINF
%define HAVE_ISINF 0
%endif
%ifndef HAVE_ISNAN
%define HAVE_ISNAN 0
%endif
%ifndef HAVE_KBHIT
%define HAVE_KBHIT 0
%endif
%ifndef HAVE_KCMVIDEOCODECTYPE_AV1
%define HAVE_KCMVIDEOCODECTYPE_AV1 0
%endif
%ifndef HAVE_KCMVIDEOCODECTYPE_HEVC
%define HAVE_KCMVIDEOCODECTYPE_HEVC 0
%endif
%ifndef HAVE_KCMVIDEOCODECTYPE_HEVCWITHALPHA
%define HAVE_KCMVIDEOCODECTYPE_HEVCWITHALPHA 0
%endif
%ifndef HAVE_KCMVIDEOCODECTYPE_VP9
%define HAVE_KCMVIDEOCODECTYPE_VP9 0
%endif
%ifndef HAVE_KCVIMAGEBUFFERCOLORPRIMARIES_ITU_R_2020
%define HAVE_KCVIMAGEBUFFERCOLORPRIMARIES_ITU_R_2020 0
%endif
%ifndef HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_ITU_R_2020
%define HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_ITU_R_2020 0
%endif
%ifndef HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_ITU_R_2100_HLG
%define HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_ITU_R_2100_HLG 0
%endif
%ifndef HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_LINEAR
%define HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_LINEAR 0
%endif
%ifndef HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_SMPTE_ST_2084_PQ
%define HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_SMPTE_ST_2084_PQ 0
%endif
%ifndef HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_SMPTE_ST_428_1
%define HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_SMPTE_ST_428_1 0
%endif
%ifndef HAVE_KCVIMAGEBUFFERYCBCRMATRIX_ITU_R_2020
%define HAVE_KCVIMAGEBUFFERYCBCRMATRIX_ITU_R_2020 0
%endif
%ifndef HAVE_KCVPIXELFORMATTYPE_420YPCBCR10BIPLANARVIDEORANGE
%define HAVE_KCVPIXELFORMATTYPE_420YPCBCR10BIPLANARVIDEORANGE 0
%endif
%ifndef HAVE_KCVPIXELFORMATTYPE_422YPCBCR10BIPLANARVIDEORANGE
%define HAVE_KCVPIXELFORMATTYPE_422YPCBCR10BIPLANARVIDEORANGE 0
%endif
%ifndef HAVE_KCVPIXELFORMATTYPE_422YPCBCR16BIPLANARVIDEORANGE
%define HAVE_KCVPIXELFORMATTYPE_422YPCBCR16BIPLANARVIDEORANGE 0
%endif
%ifndef HAVE_KCVPIXELFORMATTYPE_422YPCBCR8BIPLANARVIDEORANGE
%define HAVE_KCVPIXELFORMATTYPE_422YPCBCR8BIPLANARVIDEORANGE 0
%endif
%ifndef HAVE_KCVPIXELFORMATTYPE_422YPCBCR8_YUVS
%define HAVE_KCVPIXELFORMATTYPE_422YPCBCR8_YUVS 0
%endif
%ifndef HAVE_KCVPIXELFORMATTYPE_444YPCBCR10BIPLANARVIDEORANGE
%define HAVE_KCVPIXELFORMATTYPE_444YPCBCR10BIPLANARVIDEORANGE 0
%endif
%ifndef HAVE_KCVPIXELFORMATTYPE_444YPCBCR16BIPLANARVIDEORANGE
%define HAVE_KCVPIXELFORMATTYPE_444YPCBCR16BIPLANARVIDEORANGE 0
%endif
%ifndef HAVE_KCVPIXELFORMATTYPE_444YPCBCR8BIPLANARVIDEORANGE
%define HAVE_KCVPIXELFORMATTYPE_444YPCBCR8BIPLANARVIDEORANGE 0
%endif
%ifndef HAVE_KVTQPMODULATIONLEVEL_DEFAULT
%define HAVE_KVTQPMODULATIONLEVEL_DEFAULT 0
%endif
%ifndef HAVE_LASX_EXTERNAL
%define HAVE_LASX_EXTERNAL 0
%endif
%ifndef HAVE_LASX_INLINE
%define HAVE_LASX_INLINE 0
%endif
%ifndef HAVE_LDBRX_EXTERNAL
%define HAVE_LDBRX_EXTERNAL 0
%endif
%ifndef HAVE_LDBRX_INLINE
%define HAVE_LDBRX_INLINE 0
%endif
%ifndef HAVE_LDEXPF
%define HAVE_LDEXPF 0
%endif
%ifndef HAVE_LIBC_MSVCRT
%define HAVE_LIBC_MSVCRT 0
%endif
%ifndef HAVE_LIBDRM_GETFB2
%define HAVE_LIBDRM_GETFB2 0
%endif
%ifndef HAVE_LINUX_DMA_BUF_H
%define HAVE_LINUX_DMA_BUF_H 0
%endif
%ifndef HAVE_LINUX_PERF_EVENT_H
%define HAVE_LINUX_PERF_EVENT_H 0
%endif
%ifndef HAVE_LLRINT
%define HAVE_LLRINT 0
%endif
%ifndef HAVE_LLRINTF
%define HAVE_LLRINTF 0
%endif
%ifndef HAVE_LOCALTIME_R
%define HAVE_LOCALTIME_R 0
%endif
%ifndef HAVE_LOG10F
%define HAVE_LOG10F 0
%endif
%ifndef HAVE_LOG2
%define HAVE_LOG2 0
%endif
%ifndef HAVE_LOG2F
%define HAVE_LOG2F 0
%endif
%ifndef HAVE_LOONGSON2_EXTERNAL
%define HAVE_LOONGSON2_EXTERNAL 0
%endif
%ifndef HAVE_LOONGSON2_INLINE
%define HAVE_LOONGSON2_INLINE 0
%endif
%ifndef HAVE_LOONGSON3_EXTERNAL
%define HAVE_LOONGSON3_EXTERNAL 0
%endif
%ifndef HAVE_LOONGSON3_INLINE
%define HAVE_LOONGSON3_INLINE 0
%endif
%ifndef HAVE_LRINT
%define HAVE_LRINT 0
%endif
%ifndef HAVE_LRINTF
%define HAVE_LRINTF 0
%endif
%ifndef HAVE_LSTAT
%define HAVE_LSTAT 0
%endif
%ifndef HAVE_LSX_EXTERNAL
%define HAVE_LSX_EXTERNAL 0
%endif
%ifndef HAVE_LSX_INLINE
%define HAVE_LSX_INLINE 0
%endif
%ifndef HAVE_LZO1X_999_COMPRESS
%define HAVE_LZO1X_999_COMPRESS 0
%endif
%ifndef HAVE_MACH_ABSOLUTE_TIME
%define HAVE_MACH_ABSOLUTE_TIME 0
%endif
%ifndef HAVE_MAKEINFO
%define HAVE_MAKEINFO 0
%endif
%ifndef HAVE_MAKEINFO_HTML
%define HAVE_MAKEINFO_HTML 0
%endif
%ifndef HAVE_MALLOC_H
%define HAVE_MALLOC_H 0
%endif
%ifndef HAVE_MAPVIEWOFFILE
%define HAVE_MAPVIEWOFFILE 0
%endif
%ifndef HAVE_MEMALIGN
%define HAVE_MEMALIGN 0
%endif
%ifndef HAVE_MEMORYBARRIER
%define HAVE_MEMORYBARRIER 0
%endif
%ifndef HAVE_MIPS32R2_EXTERNAL
%define HAVE_MIPS32R2_EXTERNAL 0
%endif
%ifndef HAVE_MIPS32R2_INLINE
%define HAVE_MIPS32R2_INLINE 0
%endif
%ifndef HAVE_MIPS32R5_EXTERNAL
%define HAVE_MIPS32R5_EXTERNAL 0
%endif
%ifndef HAVE_MIPS32R5_INLINE
%define HAVE_MIPS32R5_INLINE 0
%endif
%ifndef HAVE_MIPS32R6_EXTERNAL
%define HAVE_MIPS32R6_EXTERNAL 0
%endif
%ifndef HAVE_MIPS32R6_INLINE
%define HAVE_MIPS32R6_INLINE 0
%endif
%ifndef HAVE_MIPS64R2_EXTERNAL
%define HAVE_MIPS64R2_EXTERNAL 0
%endif
%ifndef HAVE_MIPS64R2_INLINE
%define HAVE_MIPS64R2_INLINE 0
%endif
%ifndef HAVE_MIPS64R6_EXTERNAL
%define HAVE_MIPS64R6_EXTERNAL 0
%endif
%ifndef HAVE_MIPS64R6_INLINE
%define HAVE_MIPS64R6_INLINE 0
%endif
%ifndef HAVE_MIPSDSPR2_EXTERNAL
%define HAVE_MIPSDSPR2_EXTERNAL 0
%endif
%ifndef HAVE_MIPSDSPR2_INLINE
%define HAVE_MIPSDSPR2_INLINE 0
%endif
%ifndef HAVE_MIPSDSP_EXTERNAL
%define HAVE_MIPSDSP_EXTERNAL 0
%endif
%ifndef HAVE_MIPSDSP_INLINE
%define HAVE_MIPSDSP_INLINE 0
%endif
%ifndef HAVE_MIPSFPU_EXTERNAL
%define HAVE_MIPSFPU_EXTERNAL 0
%endif
%ifndef HAVE_MIPSFPU_INLINE
%define HAVE_MIPSFPU_INLINE 0
%endif
%ifndef HAVE_MKSTEMP
%define HAVE_MKSTEMP 0
%endif
%ifndef HAVE_MMAL_PARAMETER_VIDEO_MAX_NUM_CALLBACKS
%define HAVE_MMAL_PARAMETER_VIDEO_MAX_NUM_CALLBACKS 0
%endif
%ifndef HAVE_MMAP
%define HAVE_MMAP 0
%endif
%ifndef HAVE_MMI_EXTERNAL
%define HAVE_MMI_EXTERNAL 0
%endif
%ifndef HAVE_MMI_INLINE
%define HAVE_MMI_INLINE 0
%endif
%ifndef HAVE_MMXEXT_EXTERNAL
%define HAVE_MMXEXT_EXTERNAL 0
%endif
%ifndef HAVE_MMXEXT_INLINE
%define HAVE_MMXEXT_INLINE 0
%endif
%ifndef HAVE_MMX_EXTERNAL
%define HAVE_MMX_EXTERNAL 0
%endif
%ifndef HAVE_MMX_INLINE
%define HAVE_MMX_INLINE 0
%endif
%ifndef HAVE_MM_EMPTY
%define HAVE_MM_EMPTY 0
%endif
%ifndef HAVE_MPROTECT
%define HAVE_MPROTECT 0
%endif
%ifndef HAVE_MSA_EXTERNAL
%define HAVE_MSA_EXTERNAL 0
%endif
%ifndef HAVE_MSA_INLINE
%define HAVE_MSA_INLINE 0
%endif
%ifndef HAVE_NANOSLEEP
%define HAVE_NANOSLEEP 0
%endif
%ifndef HAVE_NEON_EXTERNAL
%define HAVE_NEON_EXTERNAL 0
%endif
%ifndef HAVE_NEON_INLINE
%define HAVE_NEON_INLINE 0
%endif
%ifndef HAVE_OPENCL_D3D11
%define HAVE_OPENCL_D3D11 0
%endif
%ifndef HAVE_OPENCL_DRM_ARM
%define HAVE_OPENCL_DRM_ARM 0
%endif
%ifndef HAVE_OPENCL_DRM_BEIGNET
%define HAVE_OPENCL_DRM_BEIGNET 0
%endif
%ifndef HAVE_OPENCL_DXVA2
%define HAVE_OPENCL_DXVA2 0
%endif
%ifndef HAVE_OPENCL_VAAPI_BEIGNET
%define HAVE_OPENCL_VAAPI_BEIGNET 0
%endif
%ifndef HAVE_OPENCL_VAAPI_INTEL_MEDIA
%define HAVE_OPENCL_VAAPI_INTEL_MEDIA 0
%endif
%ifndef HAVE_OPENCL_VIDEOTOOLBOX
%define HAVE_OPENCL_VIDEOTOOLBOX 0
%endif
%ifndef HAVE_OPENVINO2
%define HAVE_OPENVINO2 0
%endif
%ifndef HAVE_OS2THREADS
%define HAVE_OS2THREADS 0
%endif
%ifndef HAVE_PEEKNAMEDPIPE
%define HAVE_PEEKNAMEDPIPE 0
%endif
%ifndef HAVE_PERL
%define HAVE_PERL 0
%endif
%ifndef HAVE_POD2MAN
%define HAVE_POD2MAN 0
%endif
%ifndef HAVE_POLL_H
%define HAVE_POLL_H 0
%endif
%ifndef HAVE_POSIX_MEMALIGN
%define HAVE_POSIX_MEMALIGN 0
%endif
%ifndef HAVE_POWER8_EXTERNAL
%define HAVE_POWER8_EXTERNAL 0
%endif
%ifndef HAVE_POWER8_INLINE
%define HAVE_POWER8_INLINE 0
%endif
%ifndef HAVE_POWF
%define HAVE_POWF 0
%endif
%ifndef HAVE_PPC4XX_EXTERNAL
%define HAVE_PPC4XX_EXTERNAL 0
%endif
%ifndef HAVE_PPC4XX_INLINE
%define HAVE_PPC4XX_INLINE 0
%endif
%ifndef HAVE_PRAGMA_DEPRECATED
%define HAVE_PRAGMA_DEPRECATED 0
%endif
%ifndef HAVE_PRCTL
%define HAVE_PRCTL 0
%endif
%ifndef HAVE_PTHREADS
%define HAVE_PTHREADS 0
%endif
%ifndef HAVE_PTHREAD_CANCEL
%define HAVE_PTHREAD_CANCEL 0
%endif
%ifndef HAVE_PTHREAD_NP_H
%define HAVE_PTHREAD_NP_H 0
%endif
%ifndef HAVE_PTHREAD_SETNAME_NP
%define HAVE_PTHREAD_SETNAME_NP 0
%endif
%ifndef HAVE_PTHREAD_SET_NAME_NP
%define HAVE_PTHREAD_SET_NAME_NP 0
%endif
%ifndef HAVE_RDTSC
%define HAVE_RDTSC 0
%endif
%ifndef HAVE_RINT
%define HAVE_RINT 0
%endif
%ifndef HAVE_ROUND
%define HAVE_ROUND 0
%endif
%ifndef HAVE_ROUNDF
%define HAVE_ROUNDF 0
%endif
%ifndef HAVE_RSYNC_CONTIMEOUT
%define HAVE_RSYNC_CONTIMEOUT 0
%endif
%ifndef HAVE_RVV_EXTERNAL
%define HAVE_RVV_EXTERNAL 0
%endif
%ifndef HAVE_RVV_INLINE
%define HAVE_RVV_INLINE 0
%endif
%ifndef HAVE_RV_EXTERNAL
%define HAVE_RV_EXTERNAL 0
%endif
%ifndef HAVE_RV_INLINE
%define HAVE_RV_INLINE 0
%endif
%ifndef HAVE_RV_ZICBOP_EXTERNAL
%define HAVE_RV_ZICBOP_EXTERNAL 0
%endif
%ifndef HAVE_RV_ZICBOP_INLINE
%define HAVE_RV_ZICBOP_INLINE 0
%endif
%ifndef HAVE_RV_ZVBB_EXTERNAL
%define HAVE_RV_ZVBB_EXTERNAL 0
%endif
%ifndef HAVE_RV_ZVBB_INLINE
%define HAVE_RV_ZVBB_INLINE 0
%endif
%ifndef HAVE_SCHED_GETAFFINITY
%define HAVE_SCHED_GETAFFINITY 0
%endif
%ifndef HAVE_SECITEMIMPORT
%define HAVE_SECITEMIMPORT 0
%endif
%ifndef HAVE_SECPKGCONTEXT_KEYINGMATERIALINFO
%define HAVE_SECPKGCONTEXT_KEYINGMATERIALINFO 0
%endif
%ifndef HAVE_SECTION_DATA_REL_RO
%define HAVE_SECTION_DATA_REL_RO 0
%endif
%ifndef HAVE_SEM_TIMEDWAIT
%define HAVE_SEM_TIMEDWAIT 0
%endif
%ifndef HAVE_SETCONSOLECTRLHANDLER
%define HAVE_SETCONSOLECTRLHANDLER 0
%endif
%ifndef HAVE_SETCONSOLETEXTATTRIBUTE
%define HAVE_SETCONSOLETEXTATTRIBUTE 0
%endif
%ifndef HAVE_SETDLLDIRECTORY
%define HAVE_SETDLLDIRECTORY 0
%endif
%ifndef HAVE_SETEND_EXTERNAL
%define HAVE_SETEND_EXTERNAL 0
%endif
%ifndef HAVE_SETEND_INLINE
%define HAVE_SETEND_INLINE 0
%endif
%ifndef HAVE_SETMODE
%define HAVE_SETMODE 0
%endif
%ifndef HAVE_SETRLIMIT
%define HAVE_SETRLIMIT 0
%endif
%ifndef HAVE_SIMD128_EXTERNAL
%define HAVE_SIMD128_EXTERNAL 0
%endif
%ifndef HAVE_SIMD128_INLINE
%define HAVE_SIMD128_INLINE 0
%endif
%ifndef HAVE_SIMD_ALIGN_16
%define HAVE_SIMD_ALIGN_16 0
%endif
%ifndef HAVE_SIMD_ALIGN_32
%define HAVE_SIMD_ALIGN_32 0
%endif
%ifndef HAVE_SIMD_ALIGN_64
%define HAVE_SIMD_ALIGN_64 0
%endif
%ifndef HAVE_SINF
%define HAVE_SINF 0
%endif
%ifndef HAVE_SLEEP
%define HAVE_SLEEP 0
%endif
%ifndef HAVE_SME2_EXTERNAL
%define HAVE_SME2_EXTERNAL 0
%endif
%ifndef HAVE_SME2_INLINE
%define HAVE_SME2_INLINE 0
%endif
%ifndef HAVE_SME_EXTERNAL
%define HAVE_SME_EXTERNAL 0
%endif
%ifndef HAVE_SME_I16I64_EXTERNAL
%define HAVE_SME_I16I64_EXTERNAL 0
%endif
%ifndef HAVE_SME_I16I64_INLINE
%define HAVE_SME_I16I64_INLINE 0
%endif
%ifndef HAVE_SME_INLINE
%define HAVE_SME_INLINE 0
%endif
%ifndef HAVE_SOCKLEN_T
%define HAVE_SOCKLEN_T 0
%endif
%ifndef HAVE_SSE2_EXTERNAL
%define HAVE_SSE2_EXTERNAL 0
%endif
%ifndef HAVE_SSE2_INLINE
%define HAVE_SSE2_INLINE 0
%endif
%ifndef HAVE_SSE3_EXTERNAL
%define HAVE_SSE3_EXTERNAL 0
%endif
%ifndef HAVE_SSE3_INLINE
%define HAVE_SSE3_INLINE 0
%endif
%ifndef HAVE_SSE42_EXTERNAL
%define HAVE_SSE42_EXTERNAL 0
%endif
%ifndef HAVE_SSE42_INLINE
%define HAVE_SSE42_INLINE 0
%endif
%ifndef HAVE_SSE4_EXTERNAL
%define HAVE_SSE4_EXTERNAL 0
%endif
%ifndef HAVE_SSE4_INLINE
%define HAVE_SSE4_INLINE 0
%endif
%ifndef HAVE_SSE_EXTERNAL
%define HAVE_SSE_EXTERNAL 0
%endif
%ifndef HAVE_SSE_INLINE
%define HAVE_SSE_INLINE 0
%endif
%ifndef HAVE_SSSE3_EXTERNAL
%define HAVE_SSSE3_EXTERNAL 0
%endif
%ifndef HAVE_SSSE3_INLINE
%define HAVE_SSSE3_INLINE 0
%endif
%ifndef HAVE_STRERROR_R
%define HAVE_STRERROR_R 0
%endif
%ifndef HAVE_STRUCT_ADDRINFO
%define HAVE_STRUCT_ADDRINFO 0
%endif
%ifndef HAVE_STRUCT_GROUP_SOURCE_REQ
%define HAVE_STRUCT_GROUP_SOURCE_REQ 0
%endif
%ifndef HAVE_STRUCT_IPV6_MREQ
%define HAVE_STRUCT_IPV6_MREQ 0
%endif
%ifndef HAVE_STRUCT_IP_MREQ_SOURCE
%define HAVE_STRUCT_IP_MREQ_SOURCE 0
%endif
%ifndef HAVE_STRUCT_MFXCONFIGINTERFACE
%define HAVE_STRUCT_MFXCONFIGINTERFACE 0
%endif
%ifndef HAVE_STRUCT_MSGHDR_MSG_FLAGS
%define HAVE_STRUCT_MSGHDR_MSG_FLAGS 0
%endif
%ifndef HAVE_STRUCT_POLLFD
%define HAVE_STRUCT_POLLFD 0
%endif
%ifndef HAVE_STRUCT_RUSAGE_RU_MAXRSS
%define HAVE_STRUCT_RUSAGE_RU_MAXRSS 0
%endif
%ifndef HAVE_STRUCT_SCTP_EVENT_SUBSCRIBE
%define HAVE_STRUCT_SCTP_EVENT_SUBSCRIBE 0
%endif
%ifndef HAVE_STRUCT_SOCKADDR_IN6
%define HAVE_STRUCT_SOCKADDR_IN6 0
%endif
%ifndef HAVE_STRUCT_SOCKADDR_SA_LEN
%define HAVE_STRUCT_SOCKADDR_SA_LEN 0
%endif
%ifndef HAVE_STRUCT_SOCKADDR_STORAGE
%define HAVE_STRUCT_SOCKADDR_STORAGE 0
%endif
%ifndef HAVE_STRUCT_STAT_ST_MTIM_TV_NSEC
%define HAVE_STRUCT_STAT_ST_MTIM_TV_NSEC 0
%endif
%ifndef HAVE_STRUCT_V4L2_FRMIVALENUM_DISCRETE
%define HAVE_STRUCT_V4L2_FRMIVALENUM_DISCRETE 0
%endif
%ifndef HAVE_SVE2_EXTERNAL
%define HAVE_SVE2_EXTERNAL 0
%endif
%ifndef HAVE_SVE2_INLINE
%define HAVE_SVE2_INLINE 0
%endif
%ifndef HAVE_SVE_EXTERNAL
%define HAVE_SVE_EXTERNAL 0
%endif
%ifndef HAVE_SVE_INLINE
%define HAVE_SVE_INLINE 0
%endif
%ifndef HAVE_SYMVER
%define HAVE_SYMVER 0
%endif
%ifndef HAVE_SYMVER_ASM_LABEL
%define HAVE_SYMVER_ASM_LABEL 0
%endif
%ifndef HAVE_SYMVER_GNU_ASM
%define HAVE_SYMVER_GNU_ASM 0
%endif
%ifndef HAVE_SYSCONF
%define HAVE_SYSCONF 0
%endif
%ifndef HAVE_SYSCTL
%define HAVE_SYSCTL 0
%endif
%ifndef HAVE_SYSCTLBYNAME
%define HAVE_SYSCTLBYNAME 0
%endif
%ifndef HAVE_SYS_HWPROBE_H
%define HAVE_SYS_HWPROBE_H 0
%endif
%ifndef HAVE_SYS_PARAM_H
%define HAVE_SYS_PARAM_H 0
%endif
%ifndef HAVE_SYS_RESOURCE_H
%define HAVE_SYS_RESOURCE_H 0
%endif
%ifndef HAVE_SYS_SELECT_H
%define HAVE_SYS_SELECT_H 0
%endif
%ifndef HAVE_SYS_SOUNDCARD_H
%define HAVE_SYS_SOUNDCARD_H 0
%endif
%ifndef HAVE_SYS_TIME_H
%define HAVE_SYS_TIME_H 0
%endif
%ifndef HAVE_SYS_UN_H
%define HAVE_SYS_UN_H 0
%endif
%ifndef HAVE_SYS_VIDEOIO_H
%define HAVE_SYS_VIDEOIO_H 0
%endif
%ifndef HAVE_TEMPNAM
%define HAVE_TEMPNAM 0
%endif
%ifndef HAVE_TERMIOS_H
%define HAVE_TERMIOS_H 0
%endif
%ifndef HAVE_TEXI2HTML
%define HAVE_TEXI2HTML 0
%endif
%ifndef HAVE_THREADS
%define HAVE_THREADS 0
%endif
%ifndef HAVE_TRUNC
%define HAVE_TRUNC 0
%endif
%ifndef HAVE_TRUNCF
%define HAVE_TRUNCF 0
%endif
%ifndef HAVE_UDPLITE_H
%define HAVE_UDPLITE_H 0
%endif
%ifndef HAVE_UNISTD_H
%define HAVE_UNISTD_H 0
%endif
%ifndef HAVE_USLEEP
%define HAVE_USLEEP 0
%endif
%ifndef HAVE_UTGETOSTYPEFROMSTRING
%define HAVE_UTGETOSTYPEFROMSTRING 0
%endif
%ifndef HAVE_UWP
%define HAVE_UWP 0
%endif
%ifndef HAVE_VAAPI_DRM
%define HAVE_VAAPI_DRM 0
%endif
%ifndef HAVE_VAAPI_WIN32
%define HAVE_VAAPI_WIN32 0
%endif
%ifndef HAVE_VAAPI_X11
%define HAVE_VAAPI_X11 0
%endif
%ifndef HAVE_VALGRIND_VALGRIND_H
%define HAVE_VALGRIND_VALGRIND_H 0
%endif
%ifndef HAVE_VDPAU_X11
%define HAVE_VDPAU_X11 0
%endif
%ifndef HAVE_VEC_XL_EXTERNAL
%define HAVE_VEC_XL_EXTERNAL 0
%endif
%ifndef HAVE_VEC_XL_INLINE
%define HAVE_VEC_XL_INLINE 0
%endif
%ifndef HAVE_VFPV3_EXTERNAL
%define HAVE_VFPV3_EXTERNAL 0
%endif
%ifndef HAVE_VFPV3_INLINE
%define HAVE_VFPV3_INLINE 0
%endif
%ifndef HAVE_VFP_ARGS
%define HAVE_VFP_ARGS 0
%endif
%ifndef HAVE_VFP_EXTERNAL
%define HAVE_VFP_EXTERNAL 0
%endif
%ifndef HAVE_VFP_INLINE
%define HAVE_VFP_INLINE 0
%endif
%ifndef HAVE_VIRTUALALLOC
%define HAVE_VIRTUALALLOC 0
%endif
%ifndef HAVE_VSX_EXTERNAL
%define HAVE_VSX_EXTERNAL 0
%endif
%ifndef HAVE_VSX_INLINE
%define HAVE_VSX_INLINE 0
%endif
%ifndef HAVE_W32THREADS
%define HAVE_W32THREADS 0
%endif
%ifndef HAVE_WGLGETPROCADDRESS
%define HAVE_WGLGETPROCADDRESS 0
%endif
%ifndef HAVE_WINDOWS_H
%define HAVE_WINDOWS_H 0
%endif
%ifndef HAVE_WINRT
%define HAVE_WINRT 0
%endif
%ifndef HAVE_WINSOCK2_H
%define HAVE_WINSOCK2_H 0
%endif
%ifndef HAVE_X86ASM
%define HAVE_X86ASM 0
%endif
%ifndef HAVE_XFORM_ASM
%define HAVE_XFORM_ASM 0
%endif
%ifndef HAVE_XMLLINT
%define HAVE_XMLLINT 0
%endif
%ifndef HAVE_XMM_CLOBBERS
%define HAVE_XMM_CLOBBERS 0
%endif
%ifndef HAVE_XOP_EXTERNAL
%define HAVE_XOP_EXTERNAL 0
%endif
%ifndef HAVE_XOP_INLINE
%define HAVE_XOP_INLINE 0
%endif
%ifndef HAVE_ZLIB_GZIP
%define HAVE_ZLIB_GZIP 0
%endif
%ifndef HAVE___X_ABI_CWINDOWS_CGRAPHICS_CCAPTURE_CIGRAPHICSCAPTURESESSION5
%define HAVE___X_ABI_CWINDOWS_CGRAPHICS_CCAPTURE_CIGRAPHICSCAPTURESESSION5 0
%endif
%ifndef SWS_MAX_FILTER_SIZE
%define SWS_MAX_FILTER_SIZE 256
%endif
%define HAVE_AESNI (HAVE_AESNI_INLINE || HAVE_AESNI_EXTERNAL)
%define HAVE_ALTIVEC (HAVE_ALTIVEC_INLINE || HAVE_ALTIVEC_EXTERNAL)
%define HAVE_AMD3DNOW (HAVE_AMD3DNOW_INLINE || HAVE_AMD3DNOW_EXTERNAL)
%define HAVE_AMD3DNOWEXT (HAVE_AMD3DNOWEXT_INLINE || HAVE_AMD3DNOWEXT_EXTERNAL)
%define HAVE_ARMV5TE (HAVE_ARMV5TE_INLINE || HAVE_ARMV5TE_EXTERNAL)
%define HAVE_ARMV6 (HAVE_ARMV6_INLINE || HAVE_ARMV6_EXTERNAL)
%define HAVE_ARMV6T2 (HAVE_ARMV6T2_INLINE || HAVE_ARMV6T2_EXTERNAL)
%define HAVE_ARMV8 (HAVE_ARMV8_INLINE || HAVE_ARMV8_EXTERNAL)
%define HAVE_ARM_CRC (HAVE_ARM_CRC_INLINE || HAVE_ARM_CRC_EXTERNAL)
%define HAVE_AVX (HAVE_AVX_INLINE || HAVE_AVX_EXTERNAL)
%define HAVE_AVX2 (HAVE_AVX2_INLINE || HAVE_AVX2_EXTERNAL)
%define HAVE_AVX512 (HAVE_AVX512_INLINE || HAVE_AVX512_EXTERNAL)
%define HAVE_AVX512ICL (HAVE_AVX512ICL_INLINE || HAVE_AVX512ICL_EXTERNAL)
%define HAVE_CLMUL (HAVE_CLMUL_INLINE || HAVE_CLMUL_EXTERNAL)
%define HAVE_DCBZL (HAVE_DCBZL_INLINE || HAVE_DCBZL_EXTERNAL)
%define HAVE_DOTPROD (HAVE_DOTPROD_INLINE || HAVE_DOTPROD_EXTERNAL)
%define HAVE_FMA3 (HAVE_FMA3_INLINE || HAVE_FMA3_EXTERNAL)
%define HAVE_FMA4 (HAVE_FMA4_INLINE || HAVE_FMA4_EXTERNAL)
%define HAVE_I686 (HAVE_I686_INLINE || HAVE_I686_EXTERNAL)
%define HAVE_I8MM (HAVE_I8MM_INLINE || HAVE_I8MM_EXTERNAL)
%define HAVE_LASX (HAVE_LASX_INLINE || HAVE_LASX_EXTERNAL)
%define HAVE_LDBRX (HAVE_LDBRX_INLINE || HAVE_LDBRX_EXTERNAL)
%define HAVE_LOONGSON2 (HAVE_LOONGSON2_INLINE || HAVE_LOONGSON2_EXTERNAL)
%define HAVE_LOONGSON3 (HAVE_LOONGSON3_INLINE || HAVE_LOONGSON3_EXTERNAL)
%define HAVE_LSX (HAVE_LSX_INLINE || HAVE_LSX_EXTERNAL)
%define HAVE_MIPS32R2 (HAVE_MIPS32R2_INLINE || HAVE_MIPS32R2_EXTERNAL)
%define HAVE_MIPS32R5 (HAVE_MIPS32R5_INLINE || HAVE_MIPS32R5_EXTERNAL)
%define HAVE_MIPS32R6 (HAVE_MIPS32R6_INLINE || HAVE_MIPS32R6_EXTERNAL)
%define HAVE_MIPS64R2 (HAVE_MIPS64R2_INLINE || HAVE_MIPS64R2_EXTERNAL)
%define HAVE_MIPS64R6 (HAVE_MIPS64R6_INLINE || HAVE_MIPS64R6_EXTERNAL)
%define HAVE_MIPSDSP (HAVE_MIPSDSP_INLINE || HAVE_MIPSDSP_EXTERNAL)
%define HAVE_MIPSDSPR2 (HAVE_MIPSDSPR2_INLINE || HAVE_MIPSDSPR2_EXTERNAL)
%define HAVE_MIPSFPU (HAVE_MIPSFPU_INLINE || HAVE_MIPSFPU_EXTERNAL)
%define HAVE_MMI (HAVE_MMI_INLINE || HAVE_MMI_EXTERNAL)
%define HAVE_MMX (HAVE_MMX_INLINE || HAVE_MMX_EXTERNAL)
%define HAVE_MMXEXT (HAVE_MMXEXT_INLINE || HAVE_MMXEXT_EXTERNAL)
%define HAVE_MSA (HAVE_MSA_INLINE || HAVE_MSA_EXTERNAL)
%define HAVE_NEON (HAVE_NEON_INLINE || HAVE_NEON_EXTERNAL)
%define HAVE_POWER8 (HAVE_POWER8_INLINE || HAVE_POWER8_EXTERNAL)
%define HAVE_PPC4XX (HAVE_PPC4XX_INLINE || HAVE_PPC4XX_EXTERNAL)
%define HAVE_RV (HAVE_RV_INLINE || HAVE_RV_EXTERNAL)
%define HAVE_RVV (HAVE_RVV_INLINE || HAVE_RVV_EXTERNAL)
%define HAVE_RV_ZICBOP (HAVE_RV_ZICBOP_INLINE || HAVE_RV_ZICBOP_EXTERNAL)
%define HAVE_RV_ZVBB (HAVE_RV_ZVBB_INLINE || HAVE_RV_ZVBB_EXTERNAL)
%define HAVE_SETEND (HAVE_SETEND_INLINE || HAVE_SETEND_EXTERNAL)
%define HAVE_SIMD128 (HAVE_SIMD128_INLINE || HAVE_SIMD128_EXTERNAL)
%define HAVE_SME (HAVE_SME_INLINE || HAVE_SME_EXTERNAL)
%define HAVE_SME2 (HAVE_SME2_INLINE || HAVE_SME2_EXTERNAL)
%define HAVE_SME_I16I64 (HAVE_SME_I16I64_INLINE || HAVE_SME_I16I64_EXTERNAL)
%define HAVE_SSE (HAVE_SSE_INLINE || HAVE_SSE_EXTERNAL)
%define HAVE_SSE2 (HAVE_SSE2_INLINE || HAVE_SSE2_EXTERNAL)
%define HAVE_SSE3 (HAVE_SSE3_INLINE || HAVE_SSE3_EXTERNAL)
%define HAVE_SSE4 (HAVE_SSE4_INLINE || HAVE_SSE4_EXTERNAL)
%define HAVE_SSE42 (HAVE_SSE42_INLINE || HAVE_SSE42_EXTERNAL)
%define HAVE_SSSE3 (HAVE_SSSE3_INLINE || HAVE_SSSE3_EXTERNAL)
%define HAVE_SVE (HAVE_SVE_INLINE || HAVE_SVE_EXTERNAL)
%define HAVE_SVE2 (HAVE_SVE2_INLINE || HAVE_SVE2_EXTERNAL)
%define HAVE_VEC_XL (HAVE_VEC_XL_INLINE || HAVE_VEC_XL_EXTERNAL)
%define HAVE_VFP (HAVE_VFP_INLINE || HAVE_VFP_EXTERNAL)
%define HAVE_VFPV3 (HAVE_VFPV3_INLINE || HAVE_VFPV3_EXTERNAL)
%define HAVE_VSX (HAVE_VSX_INLINE || HAVE_VSX_EXTERNAL)
%define HAVE_XOP (HAVE_XOP_INLINE || HAVE_XOP_EXTERNAL)
